import type { Metadata } from "next";
import "./globals.css";
import TanStackProvider from "./components/TanStackProvider";

export const metadata: Metadata = {
  title: "Spendy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanStackProvider>
        <body>{children}</body>
      </TanStackProvider>
    </html>
  );
}
